[package]
name = "rust-stuff"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
opencv = "0.77.0"
clap = { version = "4.1.8", features = ["derive"] }
rand = "0.8.5"
